# Generated by Django 3.1 on 2020-10-06 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_auto_20201005_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur_test',
            name='flagechecsucces',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur_test',
            name='nb_questions_non_repondues',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur_test',
            name='nb_reponses_correctes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 9, 34, 23, 545270)),
        ),
    ]
