# Generated by Django 3.1 on 2020-10-06 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_auto_20201006_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur_test',
            name='num_essai',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 10, 1, 34, 801312)),
        ),
    ]
