# Generated by Django 3.1 on 2020-10-12 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_auto_20201012_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur_test',
            name='nb_reponse_incorrectes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 10, 34, 22, 259999)),
        ),
    ]
