# Generated by Django 3.1 on 2020-11-12 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_auto_20201012_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duree',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 16, 1, 11, 878116)),
        ),
    ]
