# Generated by Django 3.1 on 2021-01-07 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0007_auto_20201112_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_test', models.CharField(max_length=100)),
                ('code_question', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1500)),
                ('poids', models.IntegerField()),
                ('code_reponse', models.CharField(max_length=100)),
                ('reponse', models.CharField(max_length=1500)),
                ('reponse_correctes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='code_question',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse',
            name='code_reponse',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='code_test',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 13, 10, 49, 586747)),
        ),
    ]
