# Generated by Django 3.1 on 2021-01-21 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0008_auto_20210107_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 22, 0, 51, 49, 343936)),
        ),
    ]
