# Generated by Django 3.1 on 2021-01-22 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0011_auto_20210122_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 22, 16, 23, 17, 530549)),
        ),
    ]
