# Generated by Django 3.1 on 2021-01-22 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0014_auto_20210122_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='duree',
        ),
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 22, 16, 31, 28, 322724)),
        ),
    ]
