# Generated by Django 3.1 on 2021-01-24 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0016_auto_20210124_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duree',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur_test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 24, 1, 0, 27, 473661)),
        ),
    ]
