# Generated by Django 3.1 on 2021-01-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0010_auto_20210122_0211'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='myuser',
            name='tests',
            field=models.ManyToManyField(through='testdb.Utilisateur_Test', to='testdb.Test'),
        ),
    ]
